spring.application.name=api

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/userprac?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=9315#PrasanjeetBiswas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.security.user.name=user
spring.security.user.password=root


# logging
logging.level.com.example.api.service.logService = debug
logging.file.name= log/Studentlogs
logging.pattern.console = %d [%thread] %-5level %logger - %msg%n